

server:
  port: 8085
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
#  swagger2:
#    enabled: true
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
logging:
  level:
    root: info
